### ISSUE TITLE
invalid folder permissions inside npm package

### ISSUE THREAD

**Issue by asokani** [xfix/number-format#1]
There's a problem with npm package in the npm registry. I don't know, who is responsible, so I hope this place is appropriate.

When I download npm package http://registry.npmjs.org/number-format/-/number-format-0.1.1.tgz there is a 'lib' and 'test' folders without eXecute permissions. 

![err1](https://cloud.githubusercontent.com/assets/1385293/19394171/31d5bbb2-9238-11e6-9352-0a1d400c84a2.png)

It makes a problem when installing this npm package using new yarn package manager. See yarnpkg/yarn#872

**Comment by sugar700** [comment]
Should be fixed now.

If this is of any help, this library is a very old project of mine, and I actually think it was packaged back when I used Windows. I suppose `npm publish` didn't handle that case well, at least back then.

**Comment by asokani** [comment]
Great, now it works. Thanks.
